### ISSUE TITLE
Generic Error

### ISSUE THREAD

**Issue by Daelon02** [mnetship/ratsio#22]
Hi, when i trying connect to nats-streaming server, I have this error, I trying use https://github.com/mnetship/ratsio/blob/master/examples/stan_subscribe.rs

Usage: /home/dekstop/{something/}target/release/message-broker <subject>
Error: GenericError("Invalid input")

**Comment by awesomike** [comment]
Hi, 
Can you show me how you tried to run the example? What did you type on the cmd line?

Kind Regards

**Comment by Daelon02** [comment]
> Hi,
> Can you show me how you tried to run the example? What did you type on the cmd line?
> 
> Kind Regards

I added ratsio on Cargo.toml and cargo run --release

**Comment by awesomike** [comment]
What happens if you run.
`cargo run --example stan_subscribe foo`

and 
`cargo run --example stan_publish foo "hi there"`
on another console?

Please make sure that you have Nats streaming server running on your local machine.

**Comment by Daelon02** [comment]
> What happens if you run.
> `cargo run --example stan_subscribe foo`
> 
> and
> `cargo run --example stan_publish foo "hi there"`
> on another console?
> 
> Please make sure that you have Nats streaming server running on your local machine.

Yep, sorry, all work)
