### ISSUE TITLE
futures 3.0 and Rust 1.39

### ISSUE THREAD

**Issue by dawid-nowak** [mnetship/ratsio#5]
I was wondering if you had any plans to refactor the code to start using futures ^0.3 and async/.await features.

**Comment by mnetship** [comment]
Yes, async/.await will be implemented by the end of Dec 2019

**Comment by humb1t** [comment]
Hi @mnetship, did you start migration? 
I'm trying to deal with actix+ratsio and it's quite a mess because both projects have different approach about working with tokio runtime.
If you didn't, maybe I could help and prepare a PR with async/.await syntax?

**Comment by humb1t** [comment]
@dawid-nowak, @mnetship I started a migration in #9. 
Basic things already done, I'm working on Streams in `src/net/connection_inner.rs` right now.
The biggest challenge is to rewrite `loop_fn` in clients and connection.

**Comment by dawid-nowak** [comment]
@dawid-nowak, @mnetship 
Fair play to you guys. If I can help with anything let me know.

**Comment by ebkalderon** [comment]
It looks like async/await is already available in `master`, albeit in an MVP state. Can this issue be closed?

**Comment by dawid-nowak** [comment]
awesome news !
