### ISSUE TITLE
Master branch does not build

### ISSUE THREAD

**Issue by geauxvirtual** [mnetship/ratsio#7]
The master branch currently does not compile.

PR #1 was merged recently, which changed method `from_options` to `connect` and method `connect` to `generate_connect` that also takes additional parameters. This broke PR #3 that was using the `connect` method for re-connection.

**Comment by mnetship** [comment]
Thanks, I've fixed compilation errors. but the master is not ready for a release. PR #1 is still breaking semantically, some futures are not polled. Do not use master in production.
